defaultEnv: test-zk
protocol: bolt
serialization: hessian2
timeoutMs: 3000
sofaRpcVersion: 5.4.0
metadataPath: metadata.yaml
envs:
  local-direct:
    mode: direct
    directUrl: bolt://127.0.0.1:12200
  test-zk:
    mode: registry
    registryProtocol: zookeeper
    registryAddress: 127.0.0.1:2181
  sofa-registry:
    mode: registry
    registryAddress: sofa://127.0.0.1:9603
